import { useState } from 'react'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { Folder, File, FileText, Image, Code, ChevronRight, ChevronLeft, Home, RefreshCw, Plus, Search, Trash2 } from 'lucide-react'
import clsx from 'clsx'

const API_BASE = '/api/files'
interface FileItem { name: string; path: string; type: 'file' | 'directory'; size: number; modified: string; isDirectory: boolean }
async function listDirectory(path: string) { const res = await fetch(`${API_BASE}/list?path=${encodeURIComponent(path)}`); return res.json() }
async function readFile(path: string) { const res = await fetch(`${API_BASE}/read?path=${encodeURIComponent(path)}`); return res.json() }
async function createDirectory(path: string) { await fetch(`${API_BASE}/mkdir`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ path }) }) }
async function deleteItem(path: string, recursive = false) { await fetch(`${API_BASE}/delete`, { method: 'DELETE', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ path, recursive }) }) }
function formatBytes(bytes: number): string { if (bytes === 0) return '0 B'; const k = 1024; const sizes = ['B', 'KB', 'MB', 'GB']; const i = Math.floor(Math.log(bytes) / Math.log(k)); return parseFloat((bytes / Math.pow(k, i)).toFixed(1)) + ' ' + sizes[i]; }
function formatDate(dateString: string): string { return new Date(dateString).toLocaleDateString('en-US', { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' }) }
function getFileIcon(name: string, isDirectory: boolean) { if (isDirectory) return Folder; const ext = name.split('.').pop()?.toLowerCase(); if (['png','jpg','jpeg','gif','svg','webp'].includes(ext)) return Image; if (['md','txt','pdf'].includes(ext)) return FileText; if (['js','ts','jsx','tsx','py','go','rs','java'].includes(ext)) return Code; return File }
function getFileColor(name: string, isDirectory: boolean) { if (isDirectory) return 'text-primary'; const ext = name.split('.').pop()?.toLowerCase(); if (['js','jsx'].includes(ext)) return 'text-yellow-400'; if (['ts','tsx'].includes(ext)) return 'text-blue-500'; return 'text-gray-400' }

export default function Files() {
  const [currentPath, setCurrentPath] = useState('/workspace')
  const [selectedFile, setSelectedFile] = useState<FileItem | null>(null)
  const [previewContent, setPreviewContent] = useState<string | null>(null)
  const [searchQuery, setSearchQuery] = useState('')
  const queryClient = useQueryClient()
  const { data, isLoading, isFetching } = useQuery({ queryKey: ['files', currentPath], queryFn: () => listDirectory(currentPath) })
  const createDirMutation = useMutation({ mutationFn: createDirectory, onSuccess: () => queryClient.invalidateQueries({ queryKey: ['files', currentPath] }) })
  const deleteMutation = useMutation({ mutationFn: ({ path, recursive }: { path: string; recursive: boolean }) => deleteItem(path, recursive), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['files', currentPath] }); setSelectedFile(null) } })
  const handleNavigate = (path: string) => { setCurrentPath(path); setSelectedFile(null); setPreviewContent(null) }
  const handleFileClick = async (file: FileItem) => { if (file.isDirectory) handleNavigate(file.path); else { setSelectedFile(file); try { const content = await readFile(file.path); setPreviewContent(content.content) } catch { setPreviewContent('Failed to load preview') } } }
  const handleDelete = (file: FileItem) => { if (confirm(`Delete ${file.name}${file.isDirectory ? ' and contents' : ''}?`)) deleteMutation.mutate({ path: file.path, recursive: file.isDirectory }) }
  const breadcrumbs = currentPath.split('/').filter(Boolean)
  const filteredFiles = data?.files?.filter(f => f.name.toLowerCase().includes(searchQuery.toLowerCase())) || []
  return (
    <div className="h-full flex flex-col">
      <div className="mb-4 flex items-center justify-between"><div><h1 className="font-orbitron text-2xl font-bold text-white mb-2">File Manager</h1><p className="text-gray-400">Browse and manage files</p></div><div className="flex items-center gap-2"><button onClick={() => { const name = prompt('Folder name:'); if (name) createDirMutation.mutate(`${currentPath}/${name}`) }} className="flex items-center gap-2 px-4 py-2 bg-primary text-space-900 font-medium rounded-lg hover:bg-primary/90 transition-colors"><Plus className="w-4 h-4" />New Folder</button><button onClick={() => queryClient.invalidateQueries({ queryKey: ['files', currentPath] })} className="p-2 bg-space-800 text-gray-400 hover:text-white rounded-lg transition-colors"><RefreshCw className={clsx('w-5 h-5', isFetching && 'animate-spin')} /></button></div></div>
      <div className="mb-4 flex items-center gap-2 text-sm"><button onClick={() => handleNavigate('/workspace')} className="flex items-center gap-1 text-gray-400 hover:text-white transition-colors"><Home className="w-4 h-4" /></button>{breadcrumbs.map((part, i) => (<div key={i} className="flex items-center gap-2"><ChevronRight className="w-4 h-4 text-gray-600" /><button onClick={() => handleNavigate('/' + breadcrumbs.slice(0, i + 1).join('/'))} className="text-gray-400 hover:text-white transition-colors capitalize">{part}</button></div>))}</div>
      <div className="mb-4 relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-500" /><input type="text" placeholder="Search files..." value={searchQuery} onChange={(e) => setSearchQuery(e.target.value)} className="w-full bg-space-800 border border-space-600 rounded-lg pl-10 pr-4 py-2.5 text-sm text-white placeholder:text-gray-500 focus:outline-none focus:border-primary" /></div>
      <div className="flex-1 overflow-hidden">{isLoading ? <div className="flex items-center justify-center h-64"><div className="flex items-center gap-3 text-gray-400"><RefreshCw className="w-5 h-5 animate-spin" /><span>Loading...</span></div></div> : filteredFiles.length === 0 ? <div className="flex flex-col items-center justify-center h-64"><Folder className="w-12 h-12 text-gray-600 mb-4" /><p className="text-gray-400">{searchQuery ? 'No matches' : 'Empty folder'}</p></div> : <div className="bg-space-800/30 rounded-xl border border-space-700/50 overflow-hidden"><table className="w-full"><thead className="bg-space-800/50"><tr className="text-left text-xs text-gray-500 uppercase"><th className="px-4 py-3 font-medium">Name</th><th className="px-4 py-3 font-medium w-24">Size</th><th className="px-4 py-3 font-medium w-40">Modified</th><th className="px-4 py-3 font-medium w-16"></th></tr></thead><tbody className="divide-y divide-space-700/50">{currentPath !== '/workspace' && <tr className="hover:bg-space-700/30 cursor-pointer transition-colors" onClick={() => handleNavigate('/' + breadcrumbs.slice(0, -1).join('/') || '/workspace')}><td className="px-4 py-3"><div className="flex items-center gap-3"><ChevronLeft className="w-5 h-5 text-gray-500" /><span className="text-gray-400">..</span></div></td><td className="px-4 py-3 text-gray-500 text-sm">-</td><td className="px-4 py-3 text-gray-500 text-sm">-</td><td className="px-4 py-3"></td></tr>}{filteredFiles.sort((a, b) => { if (a.isDirectory && !b.isDirectory) return -1; if (!a.isDirectory && b.isDirectory) return 1; return a.name.localeCompare(b.name) }).map((file) => { const Icon = getFileIcon(file.name, file.isDirectory); const color = getFileColor(file.name, file.isDirectory); return (<tr key={file.path} className={clsx('hover:bg-space-700/30 cursor-pointer transition-colors group', selectedFile?.path === file.path && 'bg-primary/10')} onClick={() => handleFileClick(file)}><td className="px-4 py-3"><div className="flex items-center gap-3"><Icon className={clsx('w-5 h-5', color)} /><span className="text-white">{file.name}</span></div></td><td className="px-4 py-3 text-gray-400 text-sm font-mono">{file.isDirectory ? '-' : formatBytes(file.size)}</td><td className="px-4 py-3 text-gray-500 text-sm">{formatDate(file.modified)}</td><td className="px-4 py-3"><button onClick={(e) => { e.stopPropagation(); handleDelete(file) }} className="p-1.5 text-gray-500 hover:text-error rounded transition-colors opacity-0 group-hover:opacity-100"><Trash2 className="w-4 h-4" /></button></td></tr>)})}</tbody></table></div></div>
      {previewContent && selectedFile && (<div className="mt-6 bg-space-800/30 rounded-xl border border-space-700/50 p-4"><div className="flex items-center justify-between mb-4"><h3 className="font-medium text-white">{selectedFile.name}</h3><button onClick={() => { setSelectedFile(null); setPreviewContent(null) }} className="text-gray-400 hover:text-white">✕</button></div><pre className="font-mono text-sm text-gray-300 whitespace-pre-wrap max-h-64 overflow-auto">{previewContent}</pre></div>)}
    </div>
  )
}